In [2]:
import numpy as np
import sys


Numpy can be used for mathematics, plotting, pandas and ML

In [4]:
new_arr = np.array([1, 2, 4, 43, 21, 34], dtype = np.int32)
print(new_arr)

[ 1  2  4 43 21 34]


In [14]:
dim_arr = np.array(
    [
    [12, 0, 32],
    [34, 5, 12]
] )
print(dim_arr)

[[12  0 32]
 [34  5 12]]


2

In [16]:
# Get the dimensions
print(dim_arr.ndim)
print(dim_arr.dtype)

int64


In [31]:
# Le us say we want to get a specific element
new_darray = np.array([
    [12, 23, 24, 45, 21, 2, 34, 21],
    [13, 33, 24, 5, 2, 2, 34.3, 41]
], dtype = np.int32)
# print array
print(new_darray)
# get shape of array
print(new_darray.shape)
# Get the dimensions
print(new_darray.ndim)

# Get a specific element, rows and columns
print(f'The number at the seventh column of second row is {new_darray[1, 6]}')

# To get everything in a given row, we use =>similar to a list )(all rows = :)
print(f'The first row has the following {new_darray[0, :]}')

# Get a specific column 
print(f'Get a column {new_darray[:, 3]}')

# Lets say I want 23, 45, 2. So it is specify the row, get the first and the last index 1 & 7, then jump two steps ahead
print(f'Steps {new_darray[0, 1:7:2]}')

# I can also change an element at a certain point
print('Change Elemnt ant the second row in the fifth column')
new_darray[1, 4] = 24.7
print(new_darray)

# I can also change an entire row or column
new_darray[:, 5] = 15
print(new_darray)
# Entire row
new_darray[1, :] = 0
print(new_darray)
##### Note: it does not return decimals because I specified/ changed the data type to an integer

[[12 23 24 45 21  2 34 21]
 [13 33 24  5  2  2 34 41]]
(2, 8)
2
The number at the seventh column of second row is 34
The first row has the following [12 23 24 45 21  2 34 21]
Get a column [45  5]
Steps [23 45  2]
Change Elemnt ant the second row in the fifth column
[[12 23 24 45 21  2 34 21]
 [13 33 24  5 24  2 34 41]]
[[12 23 24 45 21 15 34 21]
 [13 33 24  5 24 15 34 41]]
[[12 23 24 45 21 15 34 21]
 [ 0  0  0  0  0  0  0  0]]


In [ ]:
# 3 dimensional array