In [2]:
import numpy as np
import sys


Numpy can be used for mathematics, plotting, pandas and ML

In [4]:
new_arr = np.array([1, 2, 4, 43, 21, 34], dtype = np.int32)
print(new_arr)

[ 1  2  4 43 21 34]


In [14]:
dim_arr = np.array(
    [
    [12, 0, 32],
    [34, 5, 12]
] )
print(dim_arr)

[[12  0 32]
 [34  5 12]]


2

In [16]:
# Get the dimensions
print(dim_arr.ndim)
print(dim_arr.dtype)

int64
