In [2]:
import numpy as np
import sys


Numpy can be used for mathematics, plotting, pandas and ML

In [4]:
new_arr = np.array([1, 2, 4, 43, 21, 34], dtype = np.int32)
print(new_arr)

[ 1  2  4 43 21 34]


In [14]:
dim_arr = np.array(
    [
    [12, 0, 32],
    [34, 5, 12]
] )
print(dim_arr)

[[12  0 32]
 [34  5 12]]


2

In [16]:
# Get the dimensions
print(dim_arr.ndim)
print(dim_arr.dtype)

int64


In [23]:
# Le us say we want to get a specific element
new_darray = np.array([
    [12, 23, 24, 45, 21, 2, 34, 21],
    [13, 33, 24, 5, 2, 2, 34.3, 41]
], dtype = np.int32)
# print array
print(new_darray)
# get shape of array
print(new_darray.shape)
# Get the dimensions
print(new_darray.ndim)

# Get a specific element, rows and columns
print(f'The number at the seventh column of second row is {new_darray[1, 6]}')

# To get everything in a given row, we use =>similar to a list
print(f'The first row has the following {new_darray[0, :]}')

# Note: it does not return decimals because I specified/ changetr

[[12 23 24 45 21  2 34 21]
 [13 33 24  5  2  2 34 41]]
(2, 8)
2
The number at the seventh column of second row is 34
The first row has the following [12 23 24 45 21  2 34 21]
